permalink: /:year/:month/:day/:title.html
paginate: 10
# markdown: rdiscount
markdown: kramdown

# 作者信息
author: 
  name: Chengyumeng
  email: 792400644@qq.com
  link: 
  weibo: 
  github: http://chengyumeng.github.io

# 站点信息
title: Chengyumeng 的博客
description: Chengyumeng 的博客
url: http://chengyumeng.github.io
rss_url: 

# gavatar头像及Favicon
gavatar: https://avatars.githubusercontent.com/u/15684846?s=400&u=25ea22b77649279ed028173d698787e86b9ce52d&v=4
favicon: https://avatars.githubusercontent.com/u/15684846?s=400&u=25ea22b77649279ed028173d698787e86b9ce52d&v=4

# google analytics 设置
google_analytics_tracking_id: UA-108442533-1
ga:
  id: UA-108442533-1
  url: 

# disqus 设置
disqus:
  shortname: qiankunli

# gitment
gitment:
  id: ddbaadab5f5d810805c3
  secret: 13b91b306680f11a55713382529b83259ef56546

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - MachineLearning
  - Kubernetes

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
plugins:
- jekyll-paginate
